"""
Package: service
Package for the application models and service routes
This module creates and configures the Flask app and sets up the logging
and SQL database
"""
import sys
import os
import logging
from flask import Flask
from flask_restx import Api
from service.common import log_handlers  # noqa: F401, E402
from service import config

# Create Flask application
app = Flask(__name__)

app.url_map.strict_slashes = False

app.config['SECRET_KEY'] = 'secret-for-dev'
app.config['LOGGING_LEVEL'] = logging.INFO
app.config['API_KEY'] = os.getenv('API_KEY')
app.config.from_object(config)

# Document the type of authorization required
authorizations = {
    'apikey': {
        'type': 'apiKey',
        'in': 'header',
        'name': 'X-Api-Key'
    }
}

######################################################################
# Configure Swagger before initializing it
######################################################################
api = Api(app,
          version='1.0.0',
          title='Shopcarts REST API Service',
          description='This is a shopcarts server.',
          default='shopcarts',
          default_label='Shopcarts operations',
          doc='/apidocs/',  # default also could use doc='/apidocs/'
          authorizations=authorizations,
          prefix='/')
# Dependencies require we import the routes AFTER the Flask app is created
# pylint: disable=wrong-import-position, wrong-import-order
from service import routes       # noqa: E402, E261
# pylint: disable=wrong-import-position
from .common import cli_commands, error_handlers  # noqa: F401 E402
from .models import Products, Shopcarts

# Set up logging for production
log_handlers.init_logging(app, "gunicorn.error")

app.logger.info(70 * "*")
app.logger.info("  S E R V I C E   R U N N I N G  ".center(70, "*"))
app.logger.info(70 * "*")

try:
    Products.init_db(app)  # make our SQLAlchemy tables
    Shopcarts.init_db(app)
# pylint: disable=broad-except
except Exception as error:
    app.logger.critical("%s: Cannot continue", error)
    # gunicorn requires exit code 4 to stop spawning workers when they die
    sys.exit(4)

app.logger.info("Service initialized!")

# If an API Key was not provided, autogenerate one
if not app.config['API_KEY']:
    app.config['API_KEY'] = routes.generate_apikey()
    app.logger.info('Missing API Key! Autogenerated: {}'.format(app.config['API_KEY']))
